# Generated by Django 5.0.6 on 2024-07-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('slug', models.SlugField(max_length=11, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=10)),
                ('sobrenome', models.CharField(max_length=15)),
                ('ano_nascimento', models.DateField()),
                ('texto', models.TextField()),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
