# Generated by Django 5.0.6 on 2024-07-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=600)),
                ('deploy', models.URLField(max_length=300)),
                ('repository', models.URLField(max_length=300)),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.skill')),
            ],
        ),
    ]
