# Generated by Django 5.0.6 on 2024-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deploy',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
