# Generated by Django 5.0.6 on 2024-07-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_deploy_alter_project_repository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='image',
        ),
    ]
