# Generated by Django 5.0.6 on 2024-07-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
