# Generated by Django 5.0.6 on 2024-07-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_skill_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='text',
            new_name='resume',
        ),
    ]
