# Generated by Django 5.0.6 on 2024-07-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_about_conclusion_project_about_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='profile/%Y/%m/%d/')),
                ('last_name', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('about', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sobre',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/'),
        ),
    ]
