# Generated by Django 5.0.6 on 2024-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_birth_about_date_of_birth_remove_about_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='about_conclusion',
        ),
        migrations.RemoveField(
            model_name='project',
            name='about_detail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='about_intro',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
        migrations.AddField(
            model_name='project',
            name='readme',
            field=models.URLField(blank=True),
        ),
    ]
