# Generated by Django 5.0.6 on 2024-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_project_about_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
